// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVNarcK5uugtIl25xzTmZ_Iyz4mB3BoBg',
    appId: '1:1021467189728:web:4c18092b3c44f48616cb85',
    messagingSenderId: '1021467189728',
    projectId: 'local-shrinks',
    authDomain: 'local-shrinks.firebaseapp.com',
    storageBucket: 'local-shrinks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnic6JsOytZaQ24WgNOoLaMg-e9PWzvE8',
    appId: '1:1021467189728:android:402f68c078ca11b916cb85',
    messagingSenderId: '1021467189728',
    projectId: 'local-shrinks',
    storageBucket: 'local-shrinks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9jCu7punzspFjMqndJMQLicAc6DbV6Fg',
    appId: '1:1021467189728:ios:b36946393d7f626e16cb85',
    messagingSenderId: '1021467189728',
    projectId: 'local-shrinks',
    storageBucket: 'local-shrinks.appspot.com',
    iosBundleId: 'com.example.localShrinks',
  );
}
